# Generated by Django 4.1.3 on 2022-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('experiencia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='familiar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('experiencia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='familiar3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('experiencia', models.CharField(max_length=40)),
            ],
        ),
    ]
